language: objective-c
osx_image: xcode9
rvm:
  - "2.4.1"

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - OS=ios
    - OS=macos
    - OS=tvos

install:
  - gem install bundler
  - bundle install --path="./.vendor/bundle"
  - rake bootstrap

script:
  - bundle exec rake test[$OS]

after_success:
  - bundle exec danger
  - bash <(curl -s https://codecov.io/bash)
